name: TerraformGenerator
author: Hex_27
version: 1.5.3
depend: [Drycell]
api-version: 1.14
description: World Generator
main: org.terraform.main.TerraformGeneratorPlugin
load: startup
commands:
   terraform:
    description: Main command
    aliases: terra